### PR TITLE
Disk performance, Galera graphs: use descriptions

### PR DESCRIPTION
**Pull request by pschultz**
Replace HELP sections at the bottom of the dashboards with widget
descriptions.

### CODE REVIEW

**Comment by vadimtk** [comment]
Hello, please sing Percona CLA so we can merge your PR
https://github.com/percona/grafana-dashboards/blob/master/CONTRIBUTING.md

**Comment by pschultz** [comment]
Sorry for the delay, I missed the notification. I just signed the agreement (Individual).

**Comment by rnovikovP** [comment]
For now there bug in Grafana with Descriptions https://github.com/grafana/grafana/issues/7708

**Comment by pschultz** [comment]
Even with this bug the descriptions seem better to me than having to scroll up and down a lot because all the help texts are at the very bottom of the page.

**Pull request merged**
