### PR TITLE
fix: replace tooltip lib

### PR DESCRIPTION
**Pull request by fabio-silva**
Our previous tooltip lib for QAN wouldn't work properly with Grafana 9.

### CODE REVIEW

**Comment by fabio-silva** [comment]
@solovevayaroslavna @anton-bystrov please reviews this ASAP.
@artemgavrilov please sign the CLA.

**Comment by artemgavrilov** [comment]
Done ✔️

**Review by anton-bystrov — CHANGES_REQUESTED** [review]
изображение
Polystat panel is broken.

**Comment by fabio-silva** [comment]
As clarified, the plugin had its manifest removed to avoid signature verification (our pipeline process strips out some useless content from binaries and such). Because it then becomes an unsigned plugin, it has to be whitelisted on Grafana's .ini file:

```
allow_loading_unsigned_plugins = grafana-polystat-panel,vertamedia-clickhouse-datasource,pmm-app,pmm-check-panel-home,pmm-update,pmm-qan-app-panel,pmm-pt-summary-panel,pmm-pt-summary-datasource
```

**Review by anton-bystrov — APPROVED** [review]

**Pull request merged**
