### PR TITLE
PMM-1676 Parse error in Grafana dashboards due to removed count_scalar

### PR DESCRIPTION
**Pull request by phuslu**
Signed-off-by: phuslu <phuslu@hotmail.com>

### CODE REVIEW

**Comment by AlekSi** [comment]
It was dropped in Prometheus 2.0. https://github.com/prometheus/prometheus/issues/3060

**Comment by phuslu** [comment]
Yes. This PR intend to fix it by replacing `count_scalar(...)` with `scalr(count(...))`

**Comment by phuslu** [comment]
Rebased to latest master.

**Comment by AlekSi** [comment]
Thanks. We will merge it in several days.

**Comment by AlekSi** [comment]
Merged. Thank you!

**Pull request merged**
