### PR TITLE
PMM-2010 adopt network and disk latency graphs

### PR DESCRIPTION
**Pull request by delgod**

### CODE REVIEW

**Comment by rnovikovP** [comment]
@adivinho  can you resolve this conflict and apply changes to our new Home  (renamed) dashboard also. Thanks

**Comment by delgod** [comment]
@rnovikovP I rebased my changes, no conflicts right now

**Comment by adivinho** [comment]
- Combined metrics with an interval
- Added rds nodes to the hosts list for the "Disk Performance" dashboard

**Comment by ArvinDevel** [comment]
hi, I'm a new bee to Prometheus. I wonder why use complicated `rate(node_network_receive_bytes{xxx}[5m]) and irate(node_network_receive_bytes{xxx}[5m]) or xxx` query when calculate the network rate. To my knowledge, the value before `or` will be the final value when it has value, because `rate` and `irate` all has the same metrics label. Is this a way to avoid failure when `node_network_receive_bytes` not exists?

**Comment by adivinho** [comment]
Hello Arvin,
You are right it's a workaround to remove gaps in graphs when a display interval is lower than a scraping interval.

**Pull request merged**
