### PR TITLE
PMM-12070 Add Table plugin - db cluster summary

### PR DESCRIPTION
**Pull request by YashSartanpara1**
PMM-12070 Change boomtable plugin to grafana table plugin for DB cluster summary dashboard

FB - https://github.com/Percona-Lab/pmm-submodules/pull/3305#issuecomment-1658116271

Before:
dbcluster
dbcluster2

After:
dbcluster1
dbcluster3

### CODE REVIEW

**Comment by atymchuk** [comment]
@YashSartanpara1 Could you provide a feature build please?

**Comment by YashSartanpara1** [comment]
FB - https://github.com/Percona-Lab/pmm-submodules/pull/3305#issuecomment-1588909126

**Comment by atymchuk** [comment]
@YashSartanpara1 I've checked how well the panels render on the dashboard. It looks like we need to improve the configuration to make them look neat.

**Comment by YashSartanpara1** [comment]
> @YashSartanpara1 I've checked how well the panels render on the dashboard. It looks like we need to improve the configuration to make them look neat.

@atymchuk  Which configuration changes do you suggest?

**Review by atymchuk — DISMISSED** [review]
Looks good!

**Review by matejkubinec — DISMISSED** [review]

**Review by matejkubinec — APPROVED** [review]

**Pull request merged**
