### PR TITLE
Implement heartbeat graph in Replication dashboard

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Updated:

- Put the legend below
- Removed duplicate panel ID https://jira.percona.com/browse/PMM-614

**Comment by roidelapluie** [comment]
pth
Result with

```
sysbench /tmp/oltp_insert.lua run --tables=8 --table_size=20000 --threads=12 --delete_inserts=20000
```

**Comment by grypyrg** [comment]
Note: `pt-heartbeat` support was recently merged into `mysqld_exporter` by @roidelapluie 
https://github.com/prometheus/mysqld_exporter/pull/183

**Comment by roidelapluie** [comment]
@rnovikovP rebased :)

**Comment by saurav1991** [comment]
@roidelapluie can this be merged plz? Also can you suggest ant other way of fetching and plotting the heartbeat data via pmm-admin ?

**Comment by atymchuk** [comment]
Closing as outdated.

**Pull request closed without merging**
