### PR TITLE
Create ErrorParser.tsx

### PR DESCRIPTION
**Pull request by iamujjwalrawat**
Opened a PR.

hacktoberfest participation!

### CODE REVIEW

**Comment by puneet0191** [comment]
@iamujjwalrawat thanks a lot for your participation, it would be a huge help if you could provide more context on what problem this contribution is trying to solve.

**Review by iamujjwalrawat — COMMENTED** [review]
Changes Done!

**Comment by iamujjwalrawat** [comment]
> @iamujjwalrawat thanks a lot for your participation, it would be a huge help if you could provide more context on what problem this contribution is trying to solve. 

@puneet0191 Changes Done!

**Comment by atymchuk** [comment]
I understand it's a code sample that shows how to parse errors coming from mongo engine. I don't think we query mongo directly :)

But thanks anyways!

**Pull request closed without merging**
