### PR TITLE
PMM-3301 Prometheus 2.5

### PR DESCRIPTION
**Pull request by adivinho**

### CODE REVIEW

**Comment by AlekSi** [comment]
I'm sorry, but there are a lot of changes not related to Prometheus 2.5 at all. Why?

**Comment by adivinho** [comment]
> I'm sorry, but there are a lot of changes not related to Prometheus 2.5 at all. Why?

IMHO it's related to rebasing

**Comment by AlekSi** [comment]
That should be fixed.

**Comment by adivinho** [comment]
> That should be fixed.

Created new PR 
https://github.com/percona/grafana-dashboards/pull/292

**Pull request closed without merging**
