### PR TITLE
PMM-9003 add experimental dashboard db cluster

### PR DESCRIPTION
**Pull request by anton-bystrov**
[PMM-9003](https://jira.percona.com/browse/PMM-9003
)
[PMM-8977](https://jira.percona.com/browse/PMM-8977
)
[PMM-9352](https://jira.percona.com/browse/PMM-9352)
Add experimental dashboard to PMM. Add disclaimer for the experimental dashboard.

image

### CODE REVIEW

**Comment by nikita-b** [comment]
Do we have a link to PMM where we can see the dashboard? Or screenshot at least. It's not easy to review 30k lines of JSON file without any visual representation :)

**Comment by anton-bystrov** [comment]
> Do we have a link to PMM where we can see the dashboard? Or screenshot at least. It's not easy to review 30k lines of JSON file without any visual representation :)

Screen this dashboard you can see here: https://jira.percona.com/browse/PMM-9003

**Comment by atymchuk** [comment]
@anton-bystrov  Looks good, but we'd need a feature build on [pmm-submodules](https://github.com/Percona-Lab/pmm-submodules/pulls).

**Comment by anton-bystrov** [comment]
> @anton-bystrov Looks good, but we'd need a feature build on [pmm-submodules](https://github.com/Percona-Lab/pmm-submodules/pulls).
Yes, we have a FB in [pmm-submodules](https://github.com/Percona-Lab/pmm-submodules/pull/2212)

**Comment by rnovikovP** [comment]
@rasika-chivate, pls check the text   from the https://jira.percona.com/browse/PMM-9352 and, if needed - suggest new, better text

**Review by rasika-chivate — COMMENTED** [review]
Please Rephrase the content as follows:

## Disclaimer 
This Experimental Dashboard is not a part of the official Percona Monitoring and Management (PMM) deployment and might be updated. We ship this Dashboard to obtain feedback from our users.

Once we officially release this Dashboard, it will be moved to the appropriate folder.

**Review by rnovikovP — APPROVED** [review]

**Review by rnovikovP — DISMISSED** [review]

**Review by rnovikovP — APPROVED** [review]

**Review by rasika-chivate — APPROVED** [review]

**Review by atymchuk — APPROVED** [review]

**Review by nikita-b — APPROVED** [review]

**Pull request merged**
