### PR TITLE
PMM-6671 UI tests hotfix

### PR DESCRIPTION
**Pull request by IvanaBrecherova**

### CODE REVIEW

**Comment by IvanaBrecherova** [comment]
Fixed: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/6896/pipeline
Task: https://jira.percona.com/browse/PMM-7526

**Comment by yurkovychv** [comment]
looks like it needs to be merged into `PMM-6671-add-instance-haproxy`. @lunaticusgreen am I right?

**Comment by lunaticusgreen** [comment]
@yurkovychv Yes, you're right!

**Comment by lunaticusgreen** [comment]
Fix will be added to the original branch, this PR can be closed

**Pull request closed without merging**
