### PR TITLE
Add MariaDB Group Commits to MySQL Replication

### PR DESCRIPTION
**Pull request by roidelapluie**
Group commits enables parallel replication in MariaDB 10.0 and 10.1.
Those metrics are very important when debugging replication performance
in MariaDB.

https://mariadb.com/kb/en/mariadb/group-commit-for-the-binary-log/

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by rnovikovP** [comment]
Hello Julien, please sing Percona CLA so we can merge your PR
https://github.com/percona/grafana-dashboards/blob/master/CONTRIBUTING.md

Thanks for contributing!

**Comment by roidelapluie** [comment]
Signed it yesterday

**Comment by roidelapluie** [comment]
«please sing» didn't know I needed to sing it :)

**Comment by roidelapluie** [comment]
Set minimal to 0 for Y ayis

**Pull request closed without merging**
